//ORGS
export const FETCH_ORGS_PENDING = "FETCH_ORGS_PENDING"
export const FETCH_ORGS_SUCCESS = "FETCH_ORGS_SUCCESS"
export const FETCH_ORGS_ERROR = "FETCH_ORGS_ERROR"
//SINGLE ORG
//GET
export const GET_ORG_PENDING = "GET_ORG_PENDING"
export const GET_ORG_SUCCESS = "GET_ORG_SUCCESS"
export const GET_ORG_ERROR = "GET_ORG_ERROR"
// DELETE
export const DELETE_ORG_PENDING = "DELETE_ORG_PENDING"
export const DELETE_ORG_SUCCESS = "DELETE_ORG_SUCCESS"
export const DELETE_ORG_ERROR = "DELETE_ORG_ERROR"
// UPDATE
export const UPDATE_ORG_PENDING = "UPDATE_ORG_PENDING"
export const UPDATE_ORG_SUCCESS = "UPDATE_ORG_SUCCESS"
export const UPDATE_ORG_ERROR = "UPDATE_ORG_ERROR"
// ADD
export const ADD_ORG_PENDING = "ADD_ORG_PENDING"
export const ADD_ORG_SUCCESS = "ADD_ORG_SUCCESS"
export const ADD_ORG_ERROR = "ADD_ORG_ERROR"


//TEAMS 
export const FETCH_TEAMS_PENDING = "FETCH_TEAMS_PENDING"
export const FETCH_TEAMS_SUCCESS = "FETCH_TEAMS_SUCCESS"
export const FETCH_TEAMS_ERROR = "FETCH_TEAMS_ERROR"
// SINGLE TEAM
// GET
export const GET_TEAM_PENDING = "GET_TEAM_PENDING"
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS"
export const GET_TEAM_ERROR = "GET_TEAM_ERROR" 
// DELETE
export const DELETE_TEAM_PENDING = "DELETE_TEAM_PENDING"
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS"
export const DELETE_TEAM_ERROR = "DELETE_TEAM_ERROR"
// UPDATE
export const UPDATE_TEAM_PENDING = "UPDATE_TEAM_PENDING"
export const UPDATE_TEAM_SUCCESS = "UPDATE_TEAM_SUCCESS"
export const UPDATE_TEAM_ERROR = "UPDATE_TEAM_ERROR"
// ADD
export const ADD_TEAM_PENDING = "ADD_TEAM_PENDING"
export const ADD_TEAM_SUCCESS = "ADD_TEAM_SUCCESS"
export const ADD_TEAM_ERROR = "ADD_TEAM_ERROR"


// USERS
export const FETCH_USERS_PENDING ="FETCH_USER_PENDING"
export const FETCH_USERS_SUCCESS ="FETCH_USER_SUCCESS"
export const FETCH_USERS_ERROR = "FETCH_ORGS_ERROR"
// SINGLE USER
// GET
export const GET_USER_PENDING = "GET_USER_PENDING"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"
// DELETE
export const DELETE_USER_PENDING = "DELETE_USER_PENDING"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_ERROR = "DELETE_USER_ERROR"
// UPDATE
export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"
// ADD
export const ADD_USER_PENDING = "ADD_USER_PENDING"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_ERROR = "ADD_USER_ERROR"


//LOCATIONS
export const FETCH_LOCATIONS_PENDING ="FETCH_LOCATION_PENDING"
export const FETCH_LOCATIONS_SUCCESS ="FETCH_LOCATION_SUCCESS"
export const FETCH_LOCATIONS_ERROR = "FETCH_LOCATION_ERROR"
// SINGLE LOCATION
// GET
export const GET_LOCATION_PENDING = "GET_LOCATION_PENDING"
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS"
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR"
// DELETE
export const DELETE_LOCATION_PENDING = "DELETE_LOCATION_PENDING"
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS"
export const DELETE_LOCATION_ERROR = "DELETE_LOCATION_ERROR"
// UPDATE
export const UPDATE_LOCATION_PENDING = "UPDATE_LOCATION_PENDING"
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS"
export const UPDATE_LOCATION_ERROR = "UPDATE_LOCATION_ERROR"
// ADD
export const ADD_LOCATION_PENDING = "ADD_LOCATION_PENDING"
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS"
export const ADD_LOCATION_ERROR = "ADD_LOCATION_ERROR"


//STATUSES
export const FETCH_STATUSES_PENDING = "FETCH_STATUS_PENDING"
export const FETCH_STATUSES_SUCCESS = "FETCH_STATUS_SUCCESS"
export const FETCH_STATUSES_ERROR = "FETCH_STATUS_ERROR"
// SINGLE STATUS
// GET
export const GET_STATUS_PENDING = "GET_STATUS_PENDING"
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS"
export const GET_STATUS_ERROR = "GET_STATUS_ERROR"
// DELETE
export const DELETE_STATUS_PENDING = "DELETE_STATUS_PENDING"
export const DELETE_STATUS_SUCCESS = "DELETE_STATUS_SUCCESS"
export const DELETE_STATUS_ERROR = "DELETE_STATUS_ERROR"
// UPDATE
export const UPDATE_STATUS_PENDING = "UPDATE_STATUS_PENDING"
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS"
export const UPDATE_STATUS_ERROR = "UPDATE_STATUS_ERROR"
// ADD
export const ADD_STATUS_PENDING = "ADD_STATUS_PENDING"
export const ADD_STATUS_SUCCESS = "ADD_STATUS_SUCCESS"
export const ADD_STATUS_ERROR = "ADD_STATUS_ERROR"

//LEVEL
// GET ALL
export const FETCH_LEVEL_PENDING = "FETCH_LEVEL_PENDING"
export const FETCH_LEVEL_SUCCESS = "FETCH_LEVEL_SUCCESS"
export const FETCH_LEVEL_ERROR =  "FETCH_LEVEL_ERROR"
// GET
export const GET_LEVEL_PENDING = "GET_LEVEL_PENDING"
export const GET_LEVEL_SUCCESS = "GET_LEVEL_SUCCESS"
export const GET_LEVEL_ERROR = "GET_LEVEL_ERROR"
// DELETE
export const DELETE_LEVEL_PENDING = "DELETE_LEVEL_PENDING"
export const DELETE_LEVEL_SUCCESS = "DELETE_LEVEL_SUCCESS"
export const DELETE_LEVEL_ERROR = "DELETE_LEVEL_ERROR"
// UPDATE
export const UPDATE_LEVEL_PENDING = "UPDATE_LEVEL_PENDING"
export const UPDATE_LEVEL_SUCCESS = "UPDATE_LEVEL_SUCCESS"
export const UPDATE_LEVEL_ERROR = "UPDATE_LEVEL_ERROR"
// ADD
export const ADD_LEVEL_PENDING = "ADD_LEVEL_PENDING"
export const ADD_LEVEL_SUCCESS = "ADD_LEVEL_SUCCESS"
export const ADD_LEVEL_ERROR = "ADD_LEVEL_ERROR"

//LOGIN - LOGOUT
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT = "LOGOUT"


